# Generated by Django 4.2 on 2023-04-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pergunta',
            options={'verbose_name_plural': 'perguntas'},
        ),
        migrations.RenameField(
            model_name='pergunta',
            old_name='titulo',
            new_name='enunciado',
        ),
        migrations.RemoveField(
            model_name='pergunta',
            name='data_publicacao',
        ),
        migrations.RemoveField(
            model_name='pergunta',
            name='texto',
        ),
        migrations.AddField(
            model_name='pergunta',
            name='dificuldade',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='tema',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
