# Generated by Django 4.2 on 2023-04-29 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provas', '0003_tema_alter_pergunta_tema'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('perguntas', models.ManyToManyField(to='provas.pergunta')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionarioRespondido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provas.aluno')),
                ('questionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provas.questionario')),
                ('respostas', models.ManyToManyField(to='provas.resposta')),
            ],
        ),
    ]
